### ISSUE TITLE
HW#2 Rangkuman Dito

### ISSUE THREAD

**Issue by ramadit00** [fadamsyah/icodes-intern-ms19#2]
https://www.overleaf.com/read/frgrtczbkhck

**Comment by fadamsyah** [comment]
> https://www.overleaf.com/read/frgrtczbkhck

Sippp, mantap

**Comment by fadamsyah** [comment]
> https://www.overleaf.com/read/frgrtczbkhck

Btw bab 4.1 nya kayaknya belum ya To?

**Comment by ramadit00** [comment]
Mohon maaf, saya lupa menjelaskan hubungan konstanta beta,vs, dan sr nya. Apakah sudah benar nilai \beta_1 merupakan nilai bukaan throttle maksimumnya?

**Comment by fadamsyah** [comment]
> Mohon maaf, saya lupa menjelaskan hubungan konstanta beta,vs, dan sr nya. Apakah sudah benar nilai \beta_1 merupakan nilai bukaan throttle maksimumnya?

Santai.

Bisa dibilang seperti itu dit. Kalau dari program simulasi yang dipake untuk bikin paper ini, Throttle max nya adalah 1. Nah di sini &beta;1 ngga pas sama dengan 1, karena dia _belajar_ dari data yang dikasih. Jadi dia cari nilai &beta;1 yang paling bagus supaya _loss_ atau _cost_ nya itu minimal.

**Comment by fadamsyah** [comment]
> > https://www.overleaf.com/read/frgrtczbkhck
> 
> Btw bab 4.1 nya kayaknya belum ya To?

Sorry, ini kayaknya udah ya. Ku close lagi ya
