### ISSUE TITLE
Rangkuman Axel

### ISSUE THREAD

**Issue by maxeldhiya** [fadamsyah/icodes-intern-ms19#3]
Selamat malam, mohon maaf kak agak telat karena ada kegiatan di luar sampe malam hari jadi gabisa akses laptop jadi baru bisa upload rangkuman di issue sekarang.
link rangkuman: https://www.overleaf.com/read/nbgjrkrkhfjx

**Comment by fadamsyah** [comment]
> Selamat malam, mohon maaf kak agak telat karena ada kegiatan di luar sampe malam hari jadi gabisa akses laptop jadi baru bisa upload rangkuman di issue sekarang.
> link rangkuman: https://www.overleaf.com/read/nbgjrkrkhfjx

Sip santaii

**Comment by fadamsyah** [comment]
> Selamat malam, mohon maaf kak agak telat karena ada kegiatan di luar sampe malam hari jadi gabisa akses laptop jadi baru bisa upload rangkuman di issue sekarang.
> link rangkuman: https://www.overleaf.com/read/nbgjrkrkhfjx

Izin ngasih komentar ya xel:
1. Paper ini, penulis ngga pake Neural networks untuk modelling
2. Modelling di paper ini dilakukan supaya dia punya model untuk optimasi pengontrolnya.
3. Tolong ditambahi ya, **kenapa** paper ini modelling nya pake _data-driven approach_, dan kenapa pakai FPA.
4. **Persamaan (11)**: Ini sebenernya cocokologi aja, penjelasannya ada di-paper. Penjelasan singkatnya adalah kalau kita naik kendaraan, kalau kita gas full, nanti sampai di suatu titik speed kita gabisa nambah lagi ye kan (mentok). Nah paper ini dapet ide nya dari situ, jadi gimana caranya bikin model supaya kurang lebih merepresentasikan fenomena itu. Dan fungsi yang cocok adalah 1/exponential, karen ada saturasinya.
5. Tolong ditambahin inspirasi persamaan (12) munculnya dari mana ya.
6. **Conclusion** nya kayaknya belum yak?

**Catatan umum**: Dalam menulis karya ilmiah, kita itu sangat tidak dianjurkan menulis seperti _laundry_list_, "di paper ini kita melakukan A, lalu B, lalu dilanjutkan dengan C". Harus ada motivasi/penjelasan kenapa kita melakukan A, B, dan C, lalu kenapa kita pake ini dan itu.

**Comment by maxeldhiya** [comment]
Selamat malam kak Adam, makasih untuk komentarnya, kekurangan dan kesalahan sebelumnya sudah coba saya revisi lagi dan mungkin boleh dicek lagi kak apakah masih ada yg salah/kurang. Makasih kak

**Comment by maxeldhiya** [comment]
https://www.overleaf.com/read/nbgjrkrkhfjx

**Comment by fadamsyah** [comment]
Malam  xel. Sip, udah mantepp, ku close ya
